name: mtm-notification

on:
  workflow_dispatch:
    inputs:
      MATTERMOST_WEBHOOK_URL:
        description: 'The Mattermost Incoming Webhook URL'
        required: true
      MATTERMOST_CHANNEL:
        description: 'The Mattermost channel to send the message'
        required: false
      MATTERMOST_USERNAME:
        description: 'The Mattermost username shown in the webhook'
        required: false
      MATTERMOST_ICON_URL:
        description: 'The Mattermost Icon URL for the webhook'
        required: false
      TEXT:
        description: 'The text for the webhook message'
        required: false
      PAYLOAD:
        description: 'The payload for the webhook'
        required: false

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
    - name: Mattermost
      uses: mattermost/action-mattermost-notify@2.0.0
      with:
        MATTERMOST_WEBHOOK_URL: ${{ github.event.inputs.MATTERMOST_WEBHOOK_URL }}
        MATTERMOST_CHANNEL: ${{ github.event.inputs.MATTERMOST_CHANNEL }}
        MATTERMOST_USERNAME: ${{ github.event.inputs.MATTERMOST_USERNAME }}
        MATTERMOST_ICON_URL: ${{ github.event.inputs.MATTERMOST_ICON_URL }}
        TEXT: ${{ github.event.inputs.TEXT }}
        PAYLOAD: ${{ github.event.inputs.PAYLOAD }}
